global:
  storageClassName: longhorn

diracx:
  hostname: <your_hostname>
  service:
    port: 8000
  settings:
    DIRACX_SERVICE_AUTH_ALLOWED_REDIRECTS: '["https://<your_hostname>/api/docs/oauth2-redirect","https://<your_hostname>/#authentication-callback"]'
    DIRACX_SANDBOX_STORE_BUCKET_NAME: demo-sandboxes
    DIRACX_SANDBOX_STORE_S3_CLIENT_KWARGS: '{"endpoint_url": "http://diracx-minio:9000", "aws_access_key_id": "console", "aws_secret_access_key": "console123"}'
    DIRACX_SANDBOX_STORE_AUTO_CREATE_BUCKET: "true"
  sqlDbs:
    dbs:
      AuthDB:
      JobDB:
      JobLoggingDB:
      SandboxMetadataDB:
      TaskQueueDB:
      PilotAgentsDB:
  osDbs:
    dbs:
      JobParametersDB:

ingress:
  enabled: true
  className: "traefik"
  tlsSecretName: myingress-cert
  annotations: {}

developer:
  enabled: false



dex:
  config:
    issuer: http://<your_hostname>:32002

    staticClients:
    - id: d396912e-2f04-439b-8ae7-d8c585a34790
      public: true
      name: 'CLI app'
      redirectURIs:
        - 'https://<your_hostname>/api/auth/device/complete'
        - 'https://<your_hostname>/api/auth/authorize/complete'

    staticPasswords:
      - email: "admin@example.com"
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
        username: "admin"
